### PR TITLE
Edit dates to stay utc during conversion

### PR DESCRIPTION
**Pull request by mhpjay422**
Why this PR?
- Existing dates were being converted from utc to another timezone

This PR contains: 
- edited date conversion to stay as utc after conversion

### CODE REVIEW

**Comment by mhpjay422** [comment]
CleanShot 2023-06-30 at 22 53 51@2x

**Comment by mhpjay422** [comment]
CleanShot 2023-06-30 at 22 53 51@2x

**Comment by mhpjay422** [comment]
CleanShot 2023-06-30 at 22 53 51@2x

**Comment by mhpjay422** [comment]
CleanShot 2023-06-30 at 22 53 13

**Comment by johnmosesman** [comment]
How are these getting saved in another timezone?

**Comment by mhpjay422** [comment]
Sorry, I'll expand the timezone issue here. Previously, we had instances of:

DateTime.fromJSDate()
Date.fromISO()

These convert to localtime by default

This caused a bug in the code where the date was displaying one day behind. See console logs below to show discrepancy

CleanShot 2023-07-06 at 11 53 15
CleanShot 2023-07-06 at 11 53 36@2x

**Pull request closed without merging**
