### PR TITLE
Data Updates based on 8/17 Feedback

### PR DESCRIPTION
**Pull request by colinfrederickson**
- Updates to benefits-sample-data.csv

- Updates to jobs_employees.xlsx

### CODE REVIEW

**Comment by johnmosesman** [comment]
@colinfrederickson Do you need to update the employee ID? Those IDs are specifically chosen and hardcoded into the seed data, if we update those it won't sync them. Can we update the other fields but leave the employee IDs the same?

**Comment by colinfrederickson** [comment]
@johnmosesman - we wanted to show off the API validation against the DB for the employee IDs. They will show as errors in the UI and will need to be addressed as they cause other issues with the Manager ID.

**Comment by johnmosesman** [comment]
@colinfrederickson Ah I see. Ok that will error. Do we want all of them to error or just some? Based on the benefit plan changes every record should fail validation.

**Comment by colinfrederickson** [comment]
@johnmosesman - we'll need to chat about the benefit elections. When importing benefit elections, we would want to validate that the Employee ID exists in HCM.Show before loading the benefit elections.

**Review by johnmosesman — APPROVED** [review]

**Pull request merged**
